### ISSUE TITLE
Cross and Check icon

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Artwork#9]
I created this icon hoping it would help.
The check icon is changed using Dejavu font.

**SVG**
---

![check](https://github.com/helloSystem/Artwork/assets/44593430/eba96966-26ef-4330-a1ac-366faa9af05d) ![cross](https://github.com/helloSystem/Artwork/assets/44593430/970f321a-d8f0-43a0-8b26-1e6210596b7a)

**PNG**
---
![check](https://github.com/helloSystem/Artwork/assets/44593430/746855cc-6bee-43e3-b2a0-55886dca0f4c)
![cross](https://github.com/helloSystem/Artwork/assets/44593430/468f1bbb-c53a-4f70-b3f9-639a65c97c58)

**Comment by probonopd** [comment]
Please always submit everything as pull requests. Thanks!
